title: 黒縁眼鏡は海を飛ぶ
author:
  name: ryoo14
  email: anana12185@gmail.com
  homepage:
    title: 黒縁眼鏡のお休み処
    url: https://ryoo.cc
description: >- # this means to ignore newlines until "baseurl:"
  ざっき
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.ryoo.cc" # the base hostname & protocol for your site, e.g. http://example.com
timezone: Asia/Tokyo
minima:
  social_links:
    twitter: ryoo141
    github:  ryoo14

google_analytics: UA-47086708-1

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

header_pages:
  - about.markdown

paginate: 5
paginate_path: "/page:num/"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
